#!/bin/bash

## #ddev-generated
## Description: Start storybook server or init its configuration for use with drupal/storybook module.
## Usage: storybook [args]
## Example: "ddev storybook init" or "ddev storybook start"

initStorybook() {
  if [ -f package.json ] && grep -q storybook package.json; then
    echo "Storybook seems to be already initialized. (package.json contains 'storybook')"
    exit
  fi
  touch yarn.lock
  yarn set version stable
  yarn config set nodeLinker node-modules
  # use ci mode to skip storybook automatically starting after install
  CI=true YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn dlx storybook@latest init --type server
  # remove example stories generated during initialization
  rm -rf stories
  # update example stories paths to drupal specific ones
  sed -i 's/"\.\.\/stories\/\*\*\/\*\.mdx", "\.\.\/stories\/\*\*\/\*\.stories\.@(json|yaml|yml)"/"\.\.\/web\/(modules|themes)\/\*\*\/components\/\*\*\/\*\.stories\.json"/' .storybook/main.js
  composer req drupal/storybook
  drush en storybook
  drush role:perm:add anonymous 'render storybook stories'
  exit
}

startStorybook() {
  if [ ! -f package.json ] || ! grep -q storybook package.json; then
    echo "Storybook seems to not be installed. Run "ddev storybook init" to install it."
    exit
  fi
  drush state:set twig_debug 1 --input-format=integer
  drush state:set twig_cache_disable 1 --input-format=integer
  drush state:set disable_rendered_output_cache_bins 1 --input-format=integer
  drush cache:rebuild
  supervisorctl start storybook-generate-all-stories
  supervisorctl start storybook
  exit
}

stopStorybook() {
  supervisorctl stop storybook-generate-all-stories
  supervisorctl stop storybook
  exit
}

statusStorybook() {
  supervisorctl status storybook-generate-all-stories
  supervisorctl status storybook
  exit
}

if [ $# -eq 0 ] ; then
  startStorybook
fi

case "$1" in
  init)
    initStorybook
    ;;
  start)
    startStorybook
    ;;
  stop)
    stopStorybook
    ;;
  status)
    statusStorybook
  ;;
esac
